#!/usr/bin/env phyton3
refrén = 'Csillárom, haj!'
print('Csizmadialegények')
print('\nCsizmadialegények')
print(refrén)
print('Nyolcan ülnek egy lóra')
print(refrén)
print('Úgy mennek a jó borra')
print(refrén)
print('Parancsolnak kocsmárosnak;')
print('Mérjen egy decit nyócuknak!')
print(refrén) 
print('Azt se tudják kifizetni.')
print('Az ablakon szekdesnek ki.')
print(refrén)
